CREATE TABLE times (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  jogador1 VARCHAR(255) NOT NULL,
  jogador2 VARCHAR(255) NOT NULL,
  jogador3 VARCHAR(255) NOT NULL,
  jogador4 VARCHAR(255) NOT NULL,
  jogador5 VARCHAR(255) NOT NULL
)
